// This file is automatically generated by Cosmos. Add it to .gitignore and
// only edit if you know what you're doing.

import { RendererConfig, UserModuleWrappers } from 'react-cosmos-core';

import * as fixture0 from './src/Hello.fixture.jsx';
import * as fixture1 from './src/components/test.fixture.jsx';
import * as fixture2 from './src/components/PixelArtisCard.fixture.jsx';

export const rendererConfig: RendererConfig = {
  "playgroundUrl": "http://localhost:5000",
  "rendererUrl": "http://localhost:3000/cosmos/<fixture>"
};

const fixtures = {
  'src/Hello.fixture.jsx': { module: fixture0 },
  'src/components/test.fixture.jsx': { module: fixture1 },
  'src/components/PixelArtisCard.fixture.jsx': { module: fixture2 }
};

const decorators = {};

export const moduleWrappers: UserModuleWrappers = {
  lazy: false,
  fixtures,
  decorators
};
